# Generated by Django 3.0.2 on 2020-02-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cause', models.TextField()),
                ('cities', models.TextField()),
                ('description', models.TextField()),
                ('website_link', models.URLField(max_length=520)),
                ('logo', models.ImageField(upload_to='NGOs/Logos')),
                ('categories', models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Women Empowerment', 'Women Empowerment'), ('Children', 'Children'), ('Senior Citizens', 'Senior Citizens'), ('Others', 'Others')], max_length=100)),
                ('email', models.EmailField(default='ngoxyz@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='Blogs/Images')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
        ),
    ]
